server:
  port: 8888
spring:
  datasource:
   url: jdbc:postgresql://localhost:5432/ESMS2
   username: postgres
   password: 12345

  mvc:
   view:
    prefix: /templates/
    suffix: .html
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
