server:
  port: 8888
spring:
<<<<<<< HEAD
<<<<<<< HEAD
=======

>>>>>>> 352c4d2 (add_view)
  datasource:
#   url: jdbc:postgresql://localhost:5432/ESMS2
#   username: postgres
#   password: 12345
   url: jdbc:sqlserver://TANTUYETTT;databaseName=ESMS_v3;encrypt=true;trustServerCertificate=true;
   username: sa
   password: 12345
<<<<<<< HEAD
=======
#  datasource:
#   url: jdbc:postgresql://localhost:5432/ESMS
#   username: postgres
#   password: 1
>>>>>>> 32d05800f86db541f41916264871bce87bb64cbd


  datasource:
    url: jdbc:sqlserver://localhost\MYMY:1433;database=ESMS_v3;encrypt=true;trustServerCertificate=true;loginTimeout=30;
    username: sa
    password: 1
=======

>>>>>>> 352c4d2 (add_view)
  mvc:
   view:
    prefix: /templates/
    suffix: .html
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
